export const GET_ACTORS = 'GET_ACTORS';

export const RECEIVE_ACTORS = 'RECEIVE_ACTORS';

export const GET_ACTRESSES = 'GET_ACTRESSES';

export const RECEIVE_ACTRESSES = 'RECEIVE_ACTRESSES';

export const GET_CREATIVES = 'GET_CREATIVES';

export const RECEIVE_CREATIVES = 'RECEIVE_CREATIVES';

export const RECEIVE_NEWS = 'RECEIVE_NEWS';
